#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        FUG_usb.py
#
#  Project :     FUG_usb
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      sergey.v.babenkov$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["FUG_usb", "FUG_usbClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(FUG_usb.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	FUG_usb.additionnal_import

# Device States Description
# No states for this device


class FUG_usb (PyTango.Device_4Impl):
    """FUG_usb"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(FUG_usb.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	FUG_usb.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        FUG_usb.init_device(self)
        #----- PROTECTED REGION ID(FUG_usb.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FUG_usb.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(FUG_usb.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FUG_usb.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_voltage_r_read = 0.0
        self.attr_current_r_read = 0.0
        self.attr_Ramp_function_r_read = 0
        self.attr_Ramp_rate_r_read = 0.0
        #----- PROTECTED REGION ID(FUG_usb.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FUG_usb.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(FUG_usb.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FUG_usb.always_executed_hook

    # -------------------------------------------------------------------------
    #    FUG_usb read/write attribute methods
    # -------------------------------------------------------------------------
    
    def write_voltage_w(self, attr):
        self.debug_stream("In write_voltage_w()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(FUG_usb.voltage_w_write) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FUG_usb.voltage_w_write
        
    def write_current_w(self, attr):
        self.debug_stream("In write_current_w()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(FUG_usb.current_w_write) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FUG_usb.current_w_write
        
    def read_voltage_r(self, attr):
        self.debug_stream("In read_voltage_r()")
        #----- PROTECTED REGION ID(FUG_usb.voltage_r_read) ENABLED START -----#
        attr.set_value(self.attr_voltage_r_read)
        
        #----- PROTECTED REGION END -----#	//	FUG_usb.voltage_r_read
        
    def read_current_r(self, attr):
        self.debug_stream("In read_current_r()")
        #----- PROTECTED REGION ID(FUG_usb.current_r_read) ENABLED START -----#
        attr.set_value(self.attr_current_r_read)
        
        #----- PROTECTED REGION END -----#	//	FUG_usb.current_r_read
        
    def write_hv_on(self, attr):
        self.debug_stream("In write_hv_on()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(FUG_usb.hv_on_write) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FUG_usb.hv_on_write
        
    def write_Ramp_function_w(self, attr):
        self.debug_stream("In write_Ramp_function_w()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(FUG_usb.Ramp_function_w_write) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FUG_usb.Ramp_function_w_write
        
    def write_Ramp_rate_w(self, attr):
        self.debug_stream("In write_Ramp_rate_w()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(FUG_usb.Ramp_rate_w_write) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FUG_usb.Ramp_rate_w_write
        
    def read_Ramp_function_r(self, attr):
        self.debug_stream("In read_Ramp_function_r()")
        #----- PROTECTED REGION ID(FUG_usb.Ramp_function_r_read) ENABLED START -----#
        attr.set_value(self.attr_Ramp_function_r_read)
        
        #----- PROTECTED REGION END -----#	//	FUG_usb.Ramp_function_r_read
        
    def read_Ramp_rate_r(self, attr):
        self.debug_stream("In read_Ramp_rate_r()")
        #----- PROTECTED REGION ID(FUG_usb.Ramp_rate_r_read) ENABLED START -----#
        attr.set_value(self.attr_Ramp_rate_r_read)
        
        #----- PROTECTED REGION END -----#	//	FUG_usb.Ramp_rate_r_read
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(FUG_usb.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FUG_usb.read_attr_hardware


    # -------------------------------------------------------------------------
    #    FUG_usb command methods
    # -------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(FUG_usb.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	FUG_usb.programmer_methods

class FUG_usbClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(FUG_usb.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	FUG_usb.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        'voltage_w':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'Memorized':"true"
            } ],
        'current_w':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'Memorized':"true"
            } ],
        'voltage_r':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'current_r':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'hv_on':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'Memorized':"true"
            } ],
        'Ramp_function_w':
            [[PyTango.DevLong,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'Memorized':"true"
            } ],
        'Ramp_rate_w':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'Memorized':"true"
            } ],
        'Ramp_function_r':
            [[PyTango.DevLong,
            PyTango.SCALAR,
            PyTango.READ]],
        'Ramp_rate_r':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(FUG_usbClass, FUG_usb, 'FUG_usb')
        #----- PROTECTED REGION ID(FUG_usb.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FUG_usb.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
